### ISSUE TITLE
Empty lines are recognized as an UnrecognizedIniNode

### ISSUE THREAD

**Issue by csillikd** [bash/broccolini#13]
Here
```

[section]

key=value

```
the first two empty lines are recognized as ```UnrecognizedIniNodes```, and the third one is ignored.

I think the first belongs to the section node as leading trivia, the second as trailing trivia, and the third empty line belongs to the ```KeyValueIniNode``` as trailing trivia.

It would also help to decide whether the document is well-formatted.

**Comment by tautropfli** [comment]
Agreed. Empty lines should be considered leading/trailing trivia instead of unrecognized nodes. [^1]

I don't plan on working on this soon, but I'm open to PRs :)

A couple of pointers towards a PR:
* Currently the `LeadingTrivia` and `TrailingTrivia` properties are on individual nodes. I think it would make sense to move that to the abstract `SectionChildIniNode` or even `IniNode`.
* Currently the `LeadingTrivia` and `TrailingTrivia` properties are a single `WhiteSpace` token. I would change that to an `IImmutableList<IniToken>`.
	* Don't forget to update the `GetHashCode` and `Equals` impls.
* `IniNode.NewLine` should still hold the *last* newline before the next node.
* Changing empty lines to be *leading* trivia only makes sense for the first section node and the first child node of each section. Otherwise trivia is usually *trailing* for the preceding node.
* Garbage lines (a line that has neither a `=` or `[`) should still result in `UnrecognizedIniNode`s.
* `UnrecognizedIniNode` has an internal `IsBlank()` method. That probably isn't needed anymore after your change.



[^1]: The third blank line in your example is not ignored. The final newline is included in the  `NewLine` property of your key-value node (I made the line endings explicit using `␊`):

      ```
      ␊
      [section]␊
      ␊
      key=value␊
      
      ```
      If there were two line feeds at the end of the document I would agree with you :)

**Comment by csillikd** [comment]
Tank you for the infos, I may try it!
Footnote: Yes, you are right! :D

**Comment by csillikd** [comment]
Do you plan a new release? We need that fix :)

**Comment by tautropfli** [comment]
Yes, I'm currently working on this issue :) See #17

I noticed that what we discussed needs some tweaking though:

Empty lines at the end of a section should count as trailing trivia for that section and not the last node in that section.
This will make inserting a new node at the end of the section much easier.

**Comment by tautropfli** [comment]
This is how I plan to categorize leading/trailing trivia:

![trivia-explainer](https://github.com/bash/broccolini/assets/4602612/a51fc3b3-fe77-452e-8096-753352269b51)


Does this look good to you?

**Comment by csillikd** [comment]
Looks good :)

Tau Gärtli ***@***.***> ezt írta (időpont: 2024. jún. 24., H,
18:08):

**Comment by tautropfli** [comment]
[2.0.0-rc.1](https://www.nuget.org/packages/Broccolini/2.0.0-rc.1) is published 🎉 ~~(still indexing atm)~~

I'd be grateful if you could run your internal test suite against the new version and let me know if I broke anything. If everything is good and my changes are useful I'll release 2.0.0.

**Comment by csillikd** [comment]
It works!

Tau Gärtli ***@***.***> ezt írta (időpont: 2024. jún. 25., K,
11:39):

**Comment by tautropfli** [comment]
Great! 2.0.0 is uploaded to nuget.org: https://www.nuget.org/packages/Broccolini/2.0.0

**Comment by csillikd** [comment]
🥳
Great! I have tested it only with the new tool that we develop, I trust
your tests :)

Tau Gärtli ***@***.***> ezt írta (időpont: 2024. jún. 25., K,
16:37):
